#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 ARH Laboratory
# Author: Abdelrahman Abomosa

import os
from pathlib import Path
from time import perf_counter
import numpy as np
import cv2
from pynq import Overlay, allocate
import struct

BIT_NAME = "canny.bit"
HWH_NAME = "canny.hwh"

def float_to_int(f):
    """Safely pack a Python float into a 32-bit integer for AXI-Lite registers"""
    return struct.unpack('<I', struct.pack('<f', f))[0]

def main():
    if not Path(BIT_NAME).exists() or not Path(HWH_NAME).exists():
        raise FileNotFoundError("Expected canny.bit and canny.hwh in current directory")

    print("Loading FPGA Overlay...")
    ol = Overlay(BIT_NAME)
    
    # Bind to your exact IP core name from the Vivado Block Design
    ip = ol.canny_fpga_naive_0
    
    # You can print this to see the exact memory map offsets generated by HLS!
    # print(ip.register_map)

    # 1. Load the Image
    img_path = "./images/lena.jpg"
    img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        raise FileNotFoundError(f"Could not load image at {img_path}")

    # Add this line to shrink the image and prevent AXI FIFO overflow!
    img = cv2.resize(img, (128, 128))

    rows, cols = img.shape
    img_size = rows * cols
    print(f"Loaded {img_path} ({rows}x{cols})")

    # 2. Allocate Contiguous Physical Memory for the FPGA
    print("Allocating DDR memory buffers...")
    src_buf = allocate(shape=(rows, cols), dtype=np.uint8)
    dst_buf = allocate(shape=(rows, cols), dtype=np.uint8)
    x_buf   = allocate(shape=(rows, cols), dtype=np.float32)
    y_buf   = allocate(shape=(rows, cols), dtype=np.float32)
    mag_buf = allocate(shape=(rows, cols), dtype=np.float32)
    nms_buf = allocate(shape=(rows, cols), dtype=np.float32)

    # 3. Copy image data to the contiguous input buffer
    np.copyto(src_buf, img)
    src_buf.flush() # Force CPU to flush cache so FPGA sees the data

    # 4. Map the physical addresses to the FPGA's AXI-Lite registers
    print("Configuring hardware registers...")
    ip.register_map.src = src_buf.physical_address
    ip.register_map.dst = dst_buf.physical_address
    ip.register_map.x_buf = x_buf.physical_address
    ip.register_map.y_buf = y_buf.physical_address
    ip.register_map.mag_buf = mag_buf.physical_address
    ip.register_map.nms_buf = nms_buf.physical_address
    
    ip.register_map.rows = rows
    ip.register_map.cols = cols
    ip.register_map.low_thresh = float_to_int(50.0)
    ip.register_map.high_thresh = float_to_int(150.0)

    # 5. Execute Hardware Accelerator
    print("Triggering FPGA Execution...")
    t0 = perf_counter()
    
    # Write 1 to offset 0x00 (AP_START)
    ip.write(0x00, 1)

    # Read offset 0x00 and check bit 1 (AP_DONE is 0x2)
    while not (ip.read(0x00) & 0x2):
        pass
        
    t1 = perf_counter()
    hw_time_ms = (t1 - t0) * 1e3
    print(f"Hardware execution complete! Time: {hw_time_ms:.3f} ms")

    # 6. Retrieve and Save the Result
    dst_buf.invalidate() # Force CPU to read fresh data from DDR
    
    output_dir = "../output"
    os.makedirs(output_dir, exist_ok=True)
    out_path = f"{output_dir}/lena_fpga_edges.jpg"
    cv2.imwrite(out_path, dst_buf)
    print(f"Saved edge image to {out_path}")

    # 7. Clean up memory allocations
    src_buf.close()
    dst_buf.close()
    x_buf.close()
    y_buf.close()
    mag_buf.close()
    nms_buf.close()

if __name__ == "__main__":
    main()